site_name: PurplShip
site_description: 'Shipping carriers API integration library documentation'
site_author: 'DanielK'
site_url: 'https://purplship.com'

pages:
    - Home: index.md
    - Architecture: architecture.md
    - FedEx: fedex.md
    - DHL: dhl.md
    - Reference: reference.md

theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'purple'

google_analytics:
  - 'UA-111378601-2'
  - 'auto'

markdown_extensions:
  - codehilite

# Repository
repo_name: 'PurplShip/purplship'
repo_url: 'https://github.com/PurplShip/purplship'

# Copyright
copyright: 'Copyright &copy; 2018 DanielK'