site_name: OpenShip
site_description: 'Shipping carriers API integration library documentation'
site_author: 'DanielK'
site_url: 'https://openship.xyz'

pages:
    - Home: index.md
    - Architecture: architecture.md
    - FedEx: fedex.md
    - DHL: dhl.md

theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'purple'
  favicon: 'assets/images/favicon.png'

google_analytics:
  - 'UA-111378601-2'
  - 'auto'

markdown_extensions:
  - codehilite

# Repository
repo_name: 'OpenShip/openship'
repo_url: 'https://github.com/OpenShip/openship'

# Copyright
copyright: 'Copyright &copy; 2018 DanielK'