site_name: PurplShip
site_url: https://purplship.com
site_author: PurplShip
site_description: >-
  Multi-carrier integration platform


# Repository
repo_name: purplship/purplship-server
repo_url: https://github.com/purplship/purplship-server

# Copyright
copyright: Copyright &copy; 2020 PurplShip Team

nav:
  - version 2020.4.1:
    - Introduction: index.md
    - Shipping Integration 101: 101.md
    - Library:
      - Overview: lib.overview.md
      - Fluent-API: lib.fluent.md
      - Models: lib.models.md
      - Carriers: lib.carriers.md
  - version 2019.4.0: https://archive.purplship.com

theme:
  name: material
  custom_dir: overrides
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.png

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/purplship

extra_css:
  - stylesheets/extra.css

google_analytics:
  - UA-127651907-1
  - auto